# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  mvn: scx/mvn@3.0.1
# Orchestrate or schedule a set of jobs
workflows:
    example-workflow:
      jobs:
        - mvn/build:
            command: mvn install 
            publishSonarResults: false 